dependencies = [
    {path = "resources/agents/hello-world.md", type = "agent"},
    {path = "resources/agents/anthropic/code-simplifier.md", type = "agent"},
    {path = "resources/commands/hello-world.md", type = "command"},
    {path = "resources/commands/docs.md", type = "command"},
    {handle = "dsjacobsen/go-reviewer", type = "agent"},
    {path = "resources/skills/commit", type = "skill"},
    {path = "resources/skills/agr-support", type = "skill"},
    {path = "resources/skills/release-message", type = "skill"},
    {path = "resources/skills/code-review", type = "skill"},
    {path = "resources/skills/pr", type = "skill"},
    {path = "resources/skills/seo", type = "skill"},
    {path = "resources/skills/product-strategy/growth-hacker", type = "skill"},
    {path = "resources/skills/product-strategy/jobs-theory", type = "skill"},
    {path = "resources/skills/product-strategy/flywheel", type = "skill"},
    {path = "resources/skills/product-strategy/ost", type = "skill"},
    {path = "resources/skills/anthropic/skill-creator", type = "skill"},
    {path = "resources/skills/anthropic/frontend-design", type = "skill"},
    {path = "./resources/skills/architecture-audit", type = "skill"},
    {handle = "dsjacobsen/golang-pro", type = "skill"},
    {handle = "maragudk/skills/bluesky", type = "skill"},
]
